images:
- gcr.io/jjs-dev/toolchain-gcc
- gcr.io/jjs-dev/toolchain-python3
- gcr.io/jjs-dev/toolchain-gcc-cpp
steps:
- args:
  - build
  - -t
  - gcr.io/jjs-dev/toolchain-gcc
  - -f
  - gcc/Dockerfile
  - gcc/src
  name: gcr.io/cloud-builders/docker
- args:
  - build
  - -t
  - gcr.io/jjs-dev/toolchain-python3
  - -f
  - python3/Dockerfile
  - python3/src
  name: gcr.io/cloud-builders/docker
- args:
  - build
  - -t
  - gcr.io/jjs-dev/toolchain-gcc-cpp
  - -f
  - gcc-cpp/Dockerfile
  - gcc-cpp/src
  name: gcr.io/cloud-builders/docker
