name: Build toolchains

on:
  push: 
    branches:
      - master
  pull_request: {}

env:
  IMAGE_TAG_TEMPLATE: docker.pkg.github.com/jjs-dev/toolchains/%-toolchain:latest

jobs:
  build-and-push:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build images
        run: |
          ./build.py --tag-template $IMAGE_TAG_TEMPLATE --container-manager docker
